### ISSUE TITLE
Broadcast Setting

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#1]
What steps will reproduce the problem?
1. In Network Options use Broadcast Settings

What is the expected output? What do you see instead?

SoulissApp should send a broadcast UDP/IP frame on port 230 with the IP information (address, subnetmask, gateway, SSID for WiFi and Password for WiFi).

Actually SoulissApp doesn't send any broadcast frame. Probably data are not sent because SoulissApp isn't connected with the gateway, but as configuration parameter this should be sent as broadcast.

Please note also that all the IP setting are shown in the app in a reverse way, like 0.255.255.255. This is probably due to a bigendian way to handle word.

**Comment by plinioseniore** [comment]
The functional code to set the IP address of the gateway from SoulissApp has changed as follow: 
MaCaco_SETIP            0x3D

**Comment by plinioseniore** [comment]
More details here in [Set IP Address and WiFi Parameters](https://github.com/souliss/souliss/wiki/MaCaco%20Light-Data%20Protocol#Set IP Address and WiFi Parameters) paragraph.

**Comment by shineangelic** [comment]
please confirm the following datagram is correct:

parsed bcast_IP parameter:1.2.1.4
parsed bcast_subnet parameter:0.255.255.255
parsed bcast_gateway parameter:1.0.168.192
parsed broadcast parameter:wifissid
parsed broadcast parameter:wifipass
frame debug: 0x1e 0x1d 0x17 0xff 0xff 0x6 0x39 0x3b 0x1 0x2 0x1 0x4 0x0 0xff 0xff 0xff 0x1 0x0 0xa8 0xc0 0x4 0x4 0xef 0xef 0xef 0xfd 0xef 0xef 0xfa 0xef

is this correct?

**Comment by plinioseniore** [comment]
The configuration is with three functional codes:
1) Static IP Address, Subnet Mask, IP Gateway and Souliss Gateway/Peer
configuration
2) Set SSID
3) Set Password

The description of the functional codes and the structure is here
https://github.com/souliss/souliss/wiki/MaCaco%20Light-Data%20Protocol#set-ip-address-and-wifi-parameters

Please consider that actually SoulissApp display the address is
reverse way 1.0.168.192
instead of 192.168.0.1. The order in the MaCaco frame is from left to
right, so starting from 192 over to the other numbers.

The frame should be sent as UDP broadcast. The wiki page contains only the
details on the MaCaco frame, the vNet has as usual addresses and length as
others.

Let me know if other details are required.

**Comment by shineangelic** [comment]
yes, I'd need the confirmation for reported frame parameters. Reverse IP are a separate problem, please don't consider it here. 

IP address selected is 1.2.1.4

**Comment by plinioseniore** [comment]
No is not, the frame you posted is:
0x1e 0x1d 0x17 0xff 0xff 0x6 0x39 0x3b 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff
0x1 0x0 0xa8 0xc0 0x4 0x4 0xef 0xef 0xef 0xfd 0xef 0xef 0xfa 0xef

A frame vNet + MaCaco is

0x18, 0x17, 0x17, 0xFF, 0xFF, addr, addr, 0x2D, 0x00, 0x00, Gateway/Peer,
0x0C, IP1, IP2, IP3, IP4, SB1, SB2, SB3, SB4, GW1, GW2, GW3, GW4

Where addr, addr is the vNet address for SoulissApp that was 0x06, 0x39 in
your previous example. Gateway/Peer is 0x1 for Gateway option and 0x0 for
Peer one.

To set SSID and Password just use 0x2E and 0x2F and include the SSID or
Password in the payload.

For any further detail let me know.

**Comment by shineangelic** [comment]
ok, I think we're on the good way

parsed bcast_IP parameter:1.2.3.4
parsed bcast_subnet parameter:255.255.255.0
parsed bcast_gateway parameter:192.168.0.1
parsed bcast_ssid parameter:
parsed bcast_passwd parameter:
frame debug: 0x16 0x15 0x17 0xff 0xff 0x6 0x7 0x3b 0x1 0x2 0x3 0x4 0xff 0xff 0xff 0x0 0xc0 0xa8 0x0 0x1 0x0 0x0

the payload is somehow correct, but the headers still broken :(

**Comment by plinioseniore** [comment]
Yep, you are missing the header of MaCaco.

**Comment by shineangelic** [comment]
so you mean I have to send three packets, right?

**Comment by shineangelic** [comment]
parsed bcast_IP parameter:1.2.3.4
parsed bcast_subnet parameter:255.255.255.0
parsed bcast_gateway parameter:192.168.0.1
parsed bcast_ssid parameter:6666666
parsed bcast_passwd parameter:77777777

frame debug: 0x18 0x17 0x17 0xff 0xff 0x6 0x7 0x2d 0x0 0x0 0x0 0xc 0x1 0x2 0x3 0x4 0xff 0xff 0xff 0x0 0xc0 0xa8 0x0 0x1

frame debug: 0x13 0x12 0x17 0xff 0xff 0x6 0x7 0x2e 0x0 0x0 0x0 0x7 0x36 0x36 0x36 0x36 0x36 0x36 0x36

frame debug: 0x14 0x13 0x17 0xff 0xff 0x6 0x7 0x2f 0x0 0x0 0x0 0x8 0x37 0x37 0x37 0x37 0x37 0x37 0x37 0x37

**Comment by plinioseniore** [comment]
Looks good, please consider that is required one more option as Gateway or
Peer (that can now be defined at runtime). In your example this node is a
Peer.

Please consider that you should send the SSID and Password only if are not
empty.
Don't send stop character.

Consider that in the actual SoulissApp np frame get broadcasted.

Dario.

From Mobile.

**Comment by shineangelic** [comment]
Ok for everything, apart from "Don't send stop character." What do you mean?

**Comment by plinioseniore** [comment]
Some times strings contains an ASCII stop char, so "Dario" will be 6 char
lenght and not 5 because after the o is automatically added the stop char.

In case I can change the code on the node side to match the SoulissApp
behavior.

Could you please try with Wireshark that the broadcast frame is sent out?

Thanks,
Dario.

**Comment by shineangelic** [comment]
I didn't get where you found "zeroes" in my example :/

**Comment by plinioseniore** [comment]
If your log is generated passing a string there will be no problem. To have a test, you can provide me an APK or log on a Wireshark session from your PC while sending the remote configuration.

Thanks.

**Comment by juanpintom** [comment]
Ty both for your work, if I can help just tell me :)

Regards

2015-08-27 10:58 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
you could hel sending some cellphone screenshots of the app in spanish,
needed for the market page

Thank you!

2015-08-27 15:52 GMT+02:00 juanpintom notifications@github.com:

**Comment by plinioseniore** [comment]
The Broadcast Settings formats the frames in the proper way (see below picture) but the app crash if not all data has been set. The app shall send also partial configuration based on the information that are available, following rules applies:
1) for 0x2D data that are not available shall be set at zero, always send the frame
2) for 0x2E and 0x2F if data are not available don't send out the frame

I've missed to provide an option, that is DHCP or Static IP address, this shall be set using the **Start Offset** parameter as follow:

| Mode | Start Offset Value |
| --- | --- |
| Gateway with Static IP Address | 0x01 |
| Gateway with DHCP IP Address | 0x02 |
| Peer with Static IP Address | 0x03 |
| Peer with DHCP IP Address | 0x04 |

![broadcast settings](https://cloud.githubusercontent.com/assets/10714590/9589404/688a122c-502e-11e5-9d7b-ca12fd199ae3.png)

**Comment by plinioseniore** [comment]
The Broadcast Settings is not in accordance with protocol specification, here some details:
- The **Start Offset** value doesn't follow properly the table included in the previous comment, the option Gateway with DHCP IP Address and Peer with Static IP Address works fine rather Gateway with Static IP Address and Peer with DHCP IP Address are reversed.
- The **SSID and Password** shall be sent using two different frames each one with a dedicated functional code (0x2E, 0x2F). Actually send one frame with 0x2E with both SSID and Password as Payload.

As stated in the previous comment, the frame structure was fine as before but the app was crashing. Now the app doesn't longer crash bu the frame structure is wrong.

**Comment by shineangelic** [comment]
the second bug has been corrected.

The first one seems fine:

```
 if (useDhcp){
        if (isGateway)
            startOffset=0x2;
        else
            startOffset=0x4;
    }else{
        if (isGateway)
            startOffset=0x1;
        else
            startOffset=0x3;
    }
```

gateway static 0x1
gateway dhcp 0x2
peer static 0x3
peer dhcp 0x4

seems fine...

**Comment by plinioseniore** [comment]
Likely there is a swap of the checkbox, because I get the right value only
when both are cheked or both are unchecked.

So looks like that DHCP checkbox is the Gateway one and viceversa. Probably
is a mistake on the description of the user interface.

Dario.

From Mobile.

**Comment by plinioseniore** [comment]
A couple more,

1) Please display an on-screen message once the frames has been sent out.
2) The WiFi Password is shown also after the configuration has been sent,
is better to clear that value after.

Thanks.

From Mobile.

**Comment by shineangelic** [comment]
It is impossible to swap checkboxes, because the first two combinations work fine and prove that both DHCP/peer settings are fine. Are you really sure of this? Can you make an example of wrong value?

1) a Toast is already shown, telling to the user that the packet has been sent

2)I wouldn't delete the String, maybe masquerading it ( ******\* ) is fine?

**Comment by plinioseniore** [comment]
I will test it again and let you know, should I have to test on my current APK or you will release another APK for testers only?

The Toast doesn't display in my case, i think that \* could be fine if this information could leak somehow.

**Comment by plinioseniore** [comment]
I confirm that the output values are not as on the table, from my point of view the check-boxes are swapped, because I can see the right values only when both are checked or unchecked.

Please check if on the UI the checkboxes and the read variables are connected as expected.

**Comment by plinioseniore** [comment]
Using the testing release 1.5.4 the app crashed while trying to send the broadcast frame.

**Comment by plinioseniore** [comment]
Is actually working even if the table of the **Start Offset** value is not matching with the table. Probably this is because Gateway and DHCP are with checkbox not selected so that seems reversed. But in any case, keep it as is, I will change the protocol.

**Comment by shineangelic** [comment]
are you sure? We can go on breaking it again..

**Comment by plinioseniore** [comment]
I've changed the docs and I will update the code accordingly :)
