### ISSUE TITLE
Sidebar on Lockscreen, Launcher (everywhere)

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#112]
Hi am using for a long time this app (Appsi, link to Play Store down) to add Souliss Widgets and have easy-access to the most common used commands and a link to Voice Recognition of Soulissapp this sidebar can be opened on any windows and its very usefull to control Souliss without open the app.

I ask if it's possible to have this on our app. I know we can use appsi but if weve on the app then will be good =) This is why this is just a suggestion-enhancement ;) 

Here you can see a screenshot how looks on my phone:
![screenshot_2015-11-22-19-34-32](https://cloud.githubusercontent.com/assets/7034151/11325521/57ff8fdc-9150-11e5-901a-362c10872b31.png)

https://play.google.com/store/apps/details?id=com.appsimobile.appsi&hl=es

Regards

**Comment by plinioseniore** [comment]
Hi Juan,

Alessandro will give you an answer, but now the real goal is have the SoulissApp code easy to be mantained over the future, this should give an easy transition to new Android releases.

If there is an app that does the trick, the best is share with a tutorial and don't replicate the code in SoulissApp itself. 

One of the biggest (from my point of view) step in "outsourcing" activity in SoulissApp has been the Automate and Tasker integration, that delegate a complex activity like a sequence of events. In no case we could be able to integrate in SoulissApp a such a thing, is a matter of time of course.

I really agree when you say that open an app is painfull, mostly if is for something that you do at any time. So, this app that allow shortcuts is very useful, like is useful introduce shortcuts via gesture.
As example, if I flip my phone I get a list of commands that I could apply through Automate (see screenshot below)

![screenshot_2015-11-22-19-57-07](https://cloud.githubusercontent.com/assets/10714590/11325655/78ed4812-9153-11e5-8b20-46cd4e350db6.png)

So, IMHO we should focus our self on keep code out of the app.

**Comment by juanpintom** [comment]
Hi Dario!, Ty for your answer, always :P

Good Tip, I will take a look to this option (rotating) to see the commands,
good things can be done with Automate :P

I'll make a tutorial about Appsi why I think it's a good option to have
multiple commands (widgets) with just a _swipe_ from the edge of the screen

Regards

2015-11-22 19:59 GMT+01:00 Dario Di Maio notifications@github.com:
