### ISSUE TITLE
modification main_launcher.xml

### ISSUE THREAD

**Issue by Ciucio** [souliss/soulissapp#113]
Hi. I use some small old phone (Samsung galaxy mini 2) whit cyanogenmod as touch screen. Whit 3” screen there is a problem whit button’s lay-out. I solved whit a modification of main_launcher.xml file. Look annexed files. 

[Modifica main_launcher.pdf](https://github.com/souliss/soulissapp/files/55106/Modifica.main_launcher.pdf)
[main_launcher.zip](https://github.com/souliss/soulissapp/files/55107/main_launcher.zip)

**Comment by shineangelic** [comment]
thank you for your contribution
