### ISSUE TITLE
Rebuild node doesn't delete old device

### ISSUE THREAD

**Issue by dariocdj** [souliss/soulissapp#114]
If you have -for example- 3 typicals in a node and then you delete one from arduino/esp side this doesn't disappear in node neither if you click on rebuild node nor if you click request node config.
This is not good because if you are testing some nodes then you must drop-db all times to have a real situation.

Thanks

Volevo segnalare che se ad esempio un nodo viene programmato con 3 tipici all'interno e poi ne elimini uno nel codice, questo rimane nel nodo di soulissapp, anche se clicchi ricostruisci nodo" o "richiedi configurazione nodi"...
Questo non ti permette di fare delle prove senza dover fare alla fine un drop-db

**Comment by shineangelic** [comment]
secondo me e` cosi per design, sentiamo cosa ne pensa @plinioseniore ma secondo me, se sai di aver tolto dei tipici/nodi, devi fare manualmente drop. In caso contrario, essendo il meccanismo di ricostruzione asincrono, potremmo avere dispositivi che spariscono e riappaiono.

**Comment by plinioseniore** [comment]
I agree, drop in that condition.
