### ISSUE TITLE
[BUG] T31 Inverted Cool-Heat Mode

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#118]
Hi, some users on the spanish forum notice that the T31 mode on the Soulissapp are inverted, when Cool it's selected it acts like a Heater and viceversa.

Regards

**Comment by plinioseniore** [comment]
I had a chat with @fazioa and is probably a but on SoulissApp side, have you seen if the same happen also with openHAB?

**Comment by juanpintom** [comment]
I dont tested by myself but other users on the SpML confirms that is
working well with OH. It's just a problem with the labels "cool" and
"heat", they are inverted.

Regards

2016-01-08 17:18 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
isStatusByteSet(statusByte, 7)

is this corect ?

**Comment by plinioseniore** [comment]
@fazioa has the knowledge

**Comment by fazioa** [comment]
It is BIT 8, if you start from zero

The control state bit meaning follow as:
BIT 0 (0 System OFF, 1 System ON)
BIT 1 (0 Heating OFF , 1 Heating ON)
BIT 2 (0 Cooling OFF , 1 Cooling ON)
BIT 3 (0 Fan 1 OFF , 1 Fan 1 ON)
BIT 4 (0 Fan 2 OFF , 1 Fan 2 ON)
BIT 5 (0 Fan 3 OFF , 1 Fan 3 ON)
BIT 6 (0 Manual Mode , 1 Automatic Mode for Fan)
BIT 7 (0 Heating Mode, 1 Cooling Mode)

Tonino Fazio

2016-02-24 6:42 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
inverting it is a snap, bt I'd like to understand what is not working since the impl seems OK.

yes @fazioa , it's eigth bit. How did you do un OH?

**Comment by fazioa** [comment]
Can be simply the combobox indexing?

Here binding code:
https://github.com/souliss/bindingopenhab/blob/master/openhab/bundles/binding/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/network/udp/UDPSoulissDecoder.java
from line  254

getBitState()
at line 359

Tonino Fazio

2016-02-24 19:44 GMT+01:00 Alessandro Del Pex notifications@github.com:
