### ISSUE TITLE
T16 Music Sync from Mic

### ISSUE THREAD

**Issue by dariocdj** [souliss/soulissapp#119]
A great improvement could be the possibility to choose T16 music sync from playback of the device (that is the actual way)  or from MIC of device (now i'm using a "microphone" app that listen to mic and play to speaker but it's very boring because if you pump up the volume it goes in larsen). 
Thanks
Dario

**Comment by juanpintom** [comment]
+1

2016-01-11 16:11 GMT+01:00 Dario notifications@github.com:

**Comment by shineangelic** [comment]
challenge accepted
