### ISSUE TITLE
Would it be possible to display data from mqtt sensors also in this app (feature request)

### ISSUE THREAD

**Issue by marksev1** [souliss/soulissapp#121]
Would be cool if it would it be possible to display data from mqtt sensors also in this app, so different opensource project could be mixed together and used with Souliss app...MQTT would be interesting because its the most popular protocol in IOT currently. There are lots of projects using it. Would be cool to have it for displaying or maybe in the future also toggling some stuff.

Then one could only use your app for most of the stuff, instead of using separate apps for Souliss and MQTT sensors/actuators.

**Comment by ribico** [comment]
It is possible to copy data coming from MQTT to the Souliss memory_map that is handled in the app.

**Comment by marksev1** [comment]
It sounds awesome :D. Can you maybe explain this memory map a bit more :). Does it mean that I could tie some mqtt data to a Souliss variable inside the Soulissapp (without coding in the microcontroller sketch)?

**Comment by ribico** [comment]
No, you need to code into the micro..
And you need to assign to a memory_map slot the value you get from MQTT
Souliss will handle all the rest for you.

Onestly I don't understand why you really need MQTT, except if you need to post data to external services like Adafruit.IO

Please be aware that souliss define typicals, because the way you handle a temperature is different from the way you handle a switch.
Also the user interface has to be different.

Please have a look to the doc:
https://github.com/souliss/souliss/wiki/Data%20Structure

**Comment by marksev1** [comment]
I need MQTT to be able to integrate Souliss with Node-red to use it as a controller for more advanced things, like sending sms, email, tweets, building sql-database of measurements, And building more advanced logics for example based on weather report. This Node-red is easy to use...And it has a MQTT "node", while it doesn't have a "Souliss" node, and Souliss native protocol (vnet and macaco) is too hard for me to understand to be able to decode it in Node-red. It does however have a HTTP gateway, so if in the future there will be a HTTP Gateway for Souliss I could use that.
MQTT tho' is developed just for IOT applications so should be the best for this stuff.

**Comment by ribico** [comment]
We normally use openhab for that.  Did you check it?  Souliss and openhab are almost plug and play.

**Comment by marksev1** [comment]
So the closing of this issue means that this won't be included?

**Comment by shineangelic** [comment]
the app only deals with macaco data structure included in Souliss. If you
mapped mqtt to souliss mem structure, it should already work

Alessandro

2016-03-14 15:12 GMT+01:00 marksev1 notifications@github.com:
