### ISSUE TITLE
"Rebuild node" not accesible in landscape mode

### ISSUE THREAD

**Issue by maoterodapena** [souliss/soulissapp#127]
Hi. I've been struggling with the Android app on my tablet (I'm a newbie) and couldn't get the nodes to show its devices. Later, on the phone (portrait mode, android too), I found the menu entry "Rebuild node". I double check on my phone and my tablet and yes: this option only appears in portrait mode. I think this may be an issue for people with wall-mounted tablets or just beginners like me.

I'm using the last version on playstore, 1.6.1. I've tested the 1.8.1 version too (on an Android emulator with the "demo configuration") and the problem is still there.

**Comment by shineangelic** [comment]
consider that the "rebuild node" is an emergency solution someone asked.
The "correct" way to do it is asking for model update, in Options/Model

Anyway, this is a bug

Alesandro

2016-04-20 21:16 GMT+02:00 maoterodapena notifications@github.com:

**Comment by juanpintom** [comment]
I use rebuild node many times when I update a node from Web configuration,
for me it's an useful option :)

I tested too and yes, the option isnt appears on portrait mode.

Regards
El 20/4/2016 23:46, "Alessandro Del Pex" notifications@github.com
escribió:

consider that the "rebuild node" is an emergency solution someone asked.
The "correct" way to do it is asking for model update, in Options/Model

Anyway, this is a bug

Alesandro

2016-04-20 21:16 GMT+02:00 maoterodapena notifications@github.com:
