### ISSUE TITLE
T16 fade sequence

### ISSUE THREAD

**Issue by dariocdj** [souliss/soulissapp#128]
Could be very interested to have a fade sequence from r to g, from g to b, from b to r and restart the loop. Possibly with settings of speed... 
Thanks shineangelic

**Comment by juanpintom** [comment]
Actually you can do that via code on Arduino and with a T11 to enable it
but can be a nice feature to add on Souliss App

+1

Regards

2016-04-21 19:57 GMT+02:00 Dario notifications@github.com:

**Comment by dariocdj** [comment]
Juan have you got this code? Can you share it?

Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: Juan Pinto notifications@github.com 
Data:21/04/2016  20:14  (GMT+01:00) 
A: souliss/soulissapp soulissapp@noreply.github.com 
Cc: Dario cdj@deskservice.com, Author author@noreply.github.com 
Oggetto: Re: [souliss/soulissapp] T16 fade sequence (#128) 

Actually you can do that via code on Arduino and with a T11 to enable it
but can be a nice feature to add on Souliss App

+1

Regards

2016-04-21 19:57 GMT+02:00 Dario notifications@github.com:

**Comment by juanpintom** [comment]
No I haven't
Juan have you got this code? Can you share it?

Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: Juan Pinto notifications@github.com
Data:21/04/2016 20:14 (GMT+01:00)
A: souliss/soulissapp soulissapp@noreply.github.com
Cc: Dario cdj@deskservice.com, Author author@noreply.github.com
Oggetto: Re: [souliss/soulissapp] T16 fade sequence (#128)

Actually you can do that via code on Arduino and with a T11 to enable it
but can be a nice feature to add on Souliss App

+1

Regards

2016-04-21 19:57 GMT+02:00 Dario notifications@github.com:
