### ISSUE TITLE
Souliss app Typical 19 bugs

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#13]
What steps will reproduce the problem?
1.power commands on last screen (screen where you can set the brightness) of the typical
2.It should be nice that in the scenes, you also could set the brighness. Now you can define ON, OFF & toggle for this typical
3.

What is the expected output? What do you see instead?
when you give a OFF command, the light is not going out, but the brightness is going down with one step.
When you give a power On command, the slider stays on position zero sometimes.
It seems that the power ON & OFF buttons on the last tab, are doing nearly the same as the brightness up & down.

What version of the app and framework are you using?
1.3.1

Please provide any additional information below, and use Label "App" if you
believe this is an App problem.

From https://github.com/souliss/souliss/issues/98

**Comment by shineangelic** [comment]
T19 "OFF" panel sends a 0x4 command, that according to doc:

4(hex) as command, the output move to OFF

but the brightness is decreased by one

**Comment by plinioseniore** [comment]
In the T19 code the Off command is handled in this way

``` C
// Trigger the change and save the actual color
if(memory_map[MaCaco_OUT_s + slot] != Souliss_T1n_OffCoil)
{
    memory_map[MaCaco_OUT_s + slot] = Souliss_T1n_OffCoil;      // Switch off the light state
    i_trigger = Souliss_TRIGGED;                                    // Trig the change
}

// Fade out and turn off the light step wise
    if(memory_map[MaCaco_OUT_s + slot + 1])
        memory_map[MaCaco_OUT_s + slot + 1]--;

// Once is off, reset
if((memory_map[MaCaco_OUT_s + slot + 1] == 0))
    memory_map[MaCaco_IN_s + slot] = Souliss_T1n_RstCmd;        // Reset
```

So, it decrese the output of 1 unit and then exit, but it doesn't reset the INPUT slot. So at next iteration it will find again the OffCmd and decrese of 1 again and so on.

Unfortunately if in the while some other command is sent from SoulissApp, there is the risk that it will erase the OffCmd and the light won't turn off.
To solve this we should use a while() in the code or using the AUX to indentify the last used command.

Does this explain your problem?

**Comment by plinioseniore** [comment]
I've updated the T19 in commit ee6709e67a and the problem should be solved. This applies for both friariello and ilpexfurioso braches.

Actually ilpexfurioso is up-to-date with friariello.
