### ISSUE TITLE
User and Password request on public address

### ISSUE THREAD

**Issue by choncba** [souliss/soulissapp#133]
Hi , I use souliss connected to the local WiFi and from outside through a public IP ( noip.com ) . My question is if there is a possibility that the gateway requests a username and password when trying to log in from an IP outside the local network for safety.

**Comment by plinioseniore** [comment]
Hi, in the Wiki in the page Security there is an explanation of the
Lockdown that you can use to avoid that others may access your gateway.

It will ban IP address that guess a connection.

Dario.

**Comment by choncba** [comment]
Great! Thank you Dario, this is a good option.

Luciano.
