### ISSUE TITLE
Temperature control T31

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#17]
Long story here https://github.com/souliss/souliss/issues/12

**Comment by shineangelic** [comment]
0x16 0x15 0x17 0xb1 0x0 0x6 0x6 0x33 0x0 0x0 0x0 0xa 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x7
FAN HI - T31 sul 9 SLOT

0x1a 0x19 0x17 0xb1 0x0 0x6 0x6 0x33 0x0 0x0 0x0 0xe 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xc 0x0 0x0 0x4d 0xc0
T-Set a 25 gradi sul 9 SLOT

**Comment by shineangelic** [comment]
merged to https://github.com/souliss/soulissapp/issues/36 should be ok from 1.5.3 on
