### ISSUE TITLE
When add T5x Widget Crashes App

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#20]
I know isn't implemented yet but most users don't. (bug)

 I suggest add widgets for T5x, simply show the name-value on it. (enhacement)

Regards

**Comment by juanpintom** [comment]
Still crashing, I deleted data, uninstalled previous version and instaled
again with apk from Gdrive you shared today.

It's possible add the T5x value to the widget? (with no command related)

Regards

2015-08-28 21:01 GMT+02:00 shineangelic notifications@github.com:

**Comment by shineangelic** [comment]
try now please, apk wasn't updated

**Comment by juanpintom** [comment]
Downloaded again (141) and the problem still here

Regards

**Comment by shineangelic** [comment]
Could you uninstall and get the app from the store? I tested this, it should be working, what do you mean with "141"? Correct version code is 142

**Comment by juanpintom** [comment]
It's working now, yes, 141 was the version installed, now with 142 works
well.

Ty very much! :)

Regards

2015-08-31 11:38 GMT+02:00 shineangelic notifications@github.com:
