### ISSUE TITLE
T56 logcat error

### ISSUE THREAD

**Issue by lesjaw** [souliss/soulissapp#21]
I have T56 and 57 typicals, T57  seems ok in SoulissApp, the value output seems right, but in logcat there is error..

it.angelic.soulissclient.model.typicals.SoulissTypical5nCurrentVoltagePowerSensor cannot be cast to it.angelic.soulissclient.model.ISoulissTypicalSensor

and I saw my T56 always get update, but finally there is STALE status, the value seems correct, i double check with terminal serial output in arduino

**Comment by juanpintom** [comment]
I see STALE too, but values are right.

**Comment by juanpintom** [comment]
I see STALE too, but values are right.

2015-08-19 1:37 GMT+02:00 lesjaw notifications@github.com:

**Comment by shineangelic** [comment]
the cast problem has been resolved. If you see "stale" it means the reading is old. The criteria is the same for all sensors.

Can you confirm this logic is broken? it seems working to me...

**Comment by lesjaw** [comment]
Yes... The logic is working..
