### ISSUE TITLE
Add Voice Recognition and Ok, Souliss Command

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#22]
I developed a long time ago a Voice Recognition App for Souliss on App Invertor 2, it works over Zozzariello, this app recognices the Name of Nodes and Slots automatically and have some preset words to On/Off/Toggle Commands, so we can say the words in any order and command will be sended. I've Custom Commands and can recognice sentences like "Power On Node 0 Slot 4" Its multilanguage and have an "Autostart mode"

I can share the code or whatever you need, but I want to integrate it on Souliss App and add a double clap or "Ok, Souliss" function.

Regards

**Comment by shineangelic** [comment]
in a published branch there is the new code for code recognition (https://github.com/souliss/soulissapp/tree/voiceCommands). Dario isn't happy with it tho, and I agree with him. As stated in the issue's title, 'Ok Google' should be used.

APIs to access that funcionality are somehow limited to "system actions", while custom one have to go through an approval process:
https://developers.google.com/voice-actions/custom-actions

If anyone can help is welcome, I'm quite in a dead end.

**Comment by juanpintom** [comment]
Good! I want to try this!  :)

Good work, regards

**Comment by shineangelic** [comment]
voice commands have been added to master branch. OK Google remains a chimera, for now
