### ISSUE TITLE
Add T6n

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#23]
The T6n is an Analog Setpoint stored as half-precision floating point, from SoulissApp the user can input the value that will then be used in a custom logic on the node.

SoulissApp can read back the value from the nodes in order to have values always aligned.

**Comment by ribico** [comment]
Ciao Pex, any news on this ?
My SoulissApp says : TOIMPLEMENT to a T62 slot

**Comment by shineangelic** [comment]
@ribico yes, dev started. Could you please add one to demo node? Thx

**Comment by shineangelic** [comment]
I'm sending the following:

0x1a 0x19 0x17 0xb1 0x0 0xb4 0x49 0x33 0x0 0x0 0x0 0xe 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xc0 0x4c 

to control T61 on Slot 9, but no success

**Comment by ribico** [comment]
Sure !
I will add it to the demo board on Thursday (I am away for a couple of days).
Unfortunately I have no idea about your unsuccess.

**Comment by shineangelic** [comment]
ok, thank you. If possible, add a T67, the current/voltage stuff. I know it's just MACROs, but the app part is a little trickier

**Comment by ribico** [comment]
Added with commit 8311881c2a9b1de53a3f22b8caa543cdcf3c687a.
I forgot the usb-to-serial interface today, I will flash the board tomorrow.

Did you forget to send me the App preview ?
