### ISSUE TITLE
Multicolor RGB Channels doesn't follow the actual state

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#24]
The Multicolor RGB Channel option doesn't get updated with last color used in the node, so if we change color from the wheel and then move to channels, we didn't find the same color.

**Comment by shineangelic** [comment]
can't reproduce this, in 1.5.2 seems working, but no code changed.
swapping from 'channel mode' to 'circle mode' mantains consistent color.

Someone else has this bug?

**Comment by plinioseniore** [comment]
Is the "channel" view that doesn't follow the last state. To reproduce:
Change a color from Circle view and then go in Channel view.

**Comment by shineangelic** [comment]
I believe they fixed the API on Lollipop. I confirm it's working with android 5.1

**Comment by plinioseniore** [comment]
Ok, thanks.
