### ISSUE TITLE
Release 1.5.2 confuses slot with typicals

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#33]
I've a node with 4 typicals those use 10 slot as overall. SoulissApp in the DB area report 10 typicals.

**Comment by juanpintom** [comment]
Now I cannot control my Souliss network and with OH works well.
Waiting...

Regards

**Comment by plinioseniore** [comment]
Mine is working.

**Comment by shineangelic** [comment]
which typs ?

**Comment by plinioseniore** [comment]
I've 1 RGB (4 slots) and 3 Analog values (2 slot each).

**Comment by shineangelic** [comment]
could you post a screenshot to understand better? thanks

**Comment by plinioseniore** [comment]
Haven't a screenshot, in Option/Souliss DB in DB Status is shown 10
typicals. But in the Manual menu I've 4 typicals, 10 are the slots.
Previous SoulissApp was showing the right number of typicals.

**Comment by juanpintom** [comment]
Problem solved with 142, my nodes was STALE for a few hours, but before
update was working well

Ty for your work

Regards.

2015-08-31 12:58 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
Are you sure that are we reffering to the same problem? This is coming with
the latest apk.

**Comment by juanpintom** [comment]
No, Im not sure... xD :P

I don't know why my problem (slots STALE) comes and it's solved... :S

About typicals and slots enumeration it works well for me on the lastest apk

Regards

2015-08-31 16:19 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
@plinioseniore have you used DB backup/restore functions?

**Comment by plinioseniore** [comment]
Yes, DB exported with a previous version and then restored with the latest
one. The problem araise only while importing a DB from a CSV backup,
otherwise the proper information is displayed.

**Comment by shineangelic** [comment]
OK, found the bug then. Working to solve it
