### ISSUE TITLE
Demo mode on Souliss APP

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#43]
Will be interesting for new users or curious people that want to see the capabilites of the App without a Souliss network. 

Just something similar to the Demo mode on Openhab Android App.

Regards

**Comment by ribico** [comment]
+1
Il 07/set/2015 07:46 PM, "juanpintom" notifications@github.com ha scritto:

**Comment by plinioseniore** [comment]
This require us to have a Gateway node online on a public address, I may try to have a node on the mysouliss.eu domain for public use.

**Comment by plinioseniore** [comment]
@juanpintom we have an host offered by @elminister83 so that we can have a board always available in the public that can be used for a demo. It will be only an Arduino with W5100.

Would you mind to prepare a sketch with the relevant typicals for the demo? We will not have sensor attached, so analog shall be simulated in the code.

**Comment by shineangelic** [comment]
@hatemalimam  this will also be useful for iOS development

**Comment by juanpintom** [comment]
It's ok I can work on it, I'll start a new file on my Souliss-Examples
github and we can contribute on this way.

A list of things to add?? I think will be good to add all the Typicals, on
this way the user can see all the capabilites of Souliss.

Regards

2015-09-09 16:01 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by juanpintom** [comment]
We just need the logics, no input and output commands, right?

Regards

2015-09-09 16:31 GMT+02:00 Juan Pinto juanpintom@gmail.com:

**Comment by plinioseniore** [comment]
Not too many, one per type. A light, a roller-shutter a thermostat and a couple of analog values. Yes no outputs or inputs, just a float to simulate the analog value will be enough.

**Comment by hatemalimam** [comment]
A nice to have feature. Would help a lot during the development.

**Comment by juanpintom** [comment]
Ok, I started with it.

Regards

2015-09-09 16:58 GMT+02:00 Hatem Alimam notifications@github.com:

**Comment by plinioseniore** [comment]
Ok, paste the code here once ready and with @elminister83 we will setup the node

**Comment by juanpintom** [comment]
Here I started with #define lines:
https://github.com/juanpintom/Souliss_Examples/blob/master/SoulissDemo/SoulissDemo.ino

I'll add the Set, Logic and Timer in a while :)

Regards

2015-09-09 17:22 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by juanpintom** [comment]
Ok, first attempt done:
https://github.com/juanpintom/Souliss_Examples/blob/master/SoulissDemo/SoulissDemo.ino

Isn't tested yet (im not at home), im not experienced with random() but I think its ok.

T31 and T32 are missing, but can be added.

Regards

**Comment by plinioseniore** [comment]
Hi Juan,

the sketch is exceeding the 24 slots, I think that enough to have only one analog value and skip T41 and T21.

For the analog value, keep only the temperature one and use a code like this to simulate the value:

``` C
ImportAnalog(T51,24+random(0, 100)/100*5);
Read_T51(T51);
```

This will keep the average temperature at 24+/-5 degrees.

Thanks

**Comment by juanpintom** [comment]
Ok, I'll work on it

Regards

2015-09-11 13:03 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by juanpintom** [comment]
I left this 24 slots, and show most of the typicals  I think it's important
show to user what kind of Sensors can be used and Alarm typical is
important too, what do you think?

#define T11          0    // ON/OFF Digital Output with Timer Option
#define T12          1    // ON/OFF Digital Output with AUTO mode
#define T13          2    // Digital Input Value    **RANDOM IN
#define T14          3    // Pulse Digital Output
#define T15          4    // RGB IR Light
#define T16          6    // RGB LED Strip
#define T18          10   // ON/OFF Digital Output with pulse output with
Timer Option
#define T19          11   // Dimmable Single Color LED Strip
#define T22          13   // Motorized devices with limit switches and
middle position
#define T41          14   // Anti-theft integration
                          //**************\* *\* RANDOM IN **

---

#define T52          15   // Souliss_Logic_T52 - Temperature measure (-20,
+50) °C
#define T53          17   // Souliss_Logic_T53 - Humidity measure (0, 100) %
#define T54          19   // Souliss_Logic_T54 - Light Sensor (0, 40) kLux
#define T57          21   // Souliss_Logic_T57 - Power (0, 6500)  W
#define T58          23   // Souliss_Logic_T58 - Pressure measure (0, 1500)
hPa

Regards

2015-09-11 15:26 GMT+02:00 Juan Pinto juanpintom@gmail.com:

**Comment by plinioseniore** [comment]
T41 will not play nice without an alarm source, I think we can skip it.

**Comment by juanpintom** [comment]
Yes isn't nice, but the user can see the interface.

Regards

2015-09-11 16:11 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
thank Juan for your work :)

Alessandro

2015-09-11 16:11 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by juanpintom** [comment]
Thanks to you Alessandro, this is just an sketch to show you awesome work!
:P and a simple way to show to new users their possibilities :)

T21 T51 T55 T56 are removed and an option to enable or disable T41 at line
53. Here is the sketch:
https://github.com/juanpintom/Souliss_Examples/blob/master/SoulissDemo/SoulissDemo.ino

Regards

2015-09-11 16:38 GMT+02:00 Alessandro Del Pex notifications@github.com:

**Comment by shineangelic** [comment]
what is the IP address of the demo deployment? @enricodangelo has almost finished the launcher, so I guess he'll be able to integrate it as soon as the public DEMO runtime is available

**Comment by plinioseniore** [comment]
I'm waiting for @elminister83 to keep the node online, I will provide info as soon as I will get an answer.

**Comment by marksev1** [comment]
So will one node have to be online on which this demo code will be uploaded or it wont be needed and it will be like a simulation via the android app?

**Comment by plinioseniore** [comment]
Is supposed to be a node online 24h, but actually we are looking for an hosting

**Comment by ribico** [comment]
If you like,
I could keep it in my office.
Il 09/ott/2015 08:54 AM, "Dario Di Maio" notifications@github.com ha
scritto:

**Comment by plinioseniore** [comment]
@ribico if you have a static IP address or a domain linked to a DNS and port 230 is open for incoming connection that would be great, you need a spare Arduino Ethernet or ESP8266 to connect into your network with a demo firmware (I have yet something for that).

In these days I'm also looking to Vysor, for remote access of Android phone via HTTP. Having an old Android smartphone connected to, we may also have a remote simulation for SoulissApp.

**Comment by ribico** [comment]
Static IP + DNS available
I can set the port in the firewall as well.
One or more units could be hosted, no problem.
Il 09/ott/2015 11:14 AM, "Dario Di Maio" notifications@github.com ha
scritto:

**Comment by plinioseniore** [comment]
That's great, one unit is enough for now. Let me know which kind of node you have for this we will see for the sketch.

**Comment by ribico** [comment]
I have a spare dino for now.
Il 09/ott/2015 11:28 AM, "Dario Di Maio" notifications@github.com ha
scritto:

**Comment by juanpintom** [comment]
:) Good to know, ty Ribico.

=)

Regards.

2015-10-09 12:01 GMT+02:00 ribico notifications@github.com:

**Comment by shineangelic** [comment]
Demo mode added in 1.7.0

**Comment by juanpintom** [comment]
Good! Tnx :P

Regards

2016-03-08 19:53 GMT+01:00 Alessandro Del Pex notifications@github.com:
