### ISSUE TITLE
SoulissApp Icon Set

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#44]
@shineangelic is looking for icons. I have to recover the icon set used with the last graphic upgrade of SoulissApp

**Comment by shineangelic** [comment]
not all the svg are suitable to be imported as explained on Android docs. Proceding with incremental updates

**Comment by plinioseniore** [comment]
This is just a collection of SVGs from the internet, I don't know which
criteria they meet.

From Mobile.

**Comment by shineangelic** [comment]
Version 2.0 will abandon svg and adopt font-awesome
