### ISSUE TITLE
T_19 slider not updated correctly after ON/OFF

### ISSUE THREAD

**Issue by Niels-Git** [souliss/soulissapp#52]
- manual slider (0 - 255) does not update correctly if the Power ON/OFF buttons (bottom of screen below the slider) are pushed. Nevertheless, power on LED is being turned on/off correctly.

In detail - On the 'slider screen' within typical :
E.g. power is on xx% - push button OFF - LED fades off but slider would not move to 0% brightness but stays at xx% position
E.g. power is off - push button ON - LED fades on but slider would not move to xx% brightness but stays at 0%brightness

(not checked yet if this is an issue for T_16 as well)

Niels

**Comment by shineangelic** [comment]
The slider are not moving because the brightness value is independent from light state. So, even when the lamp is turned off, the brightness value is there. For T16 is the same.

I could add a state feedback on the detail instead. What do you think?

**Comment by Niels-Git** [comment]
I see - this makes sense of course. I just was concerned, something referring the code was not correct.
Using the ON/OFF buttons of the initial typical's node-screen would result in a recent change of sliders position after changing to the'manual screen'.

Your suggestion above concerning the state feedback sounds very interesting. If it's not to much work it would be nice.

**Comment by shineangelic** [comment]
status has been added on panel, version 1.5.4
