### ISSUE TITLE
App stops working when the phone goes in standby

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#54]
While using my phone, I've SoulissApp open in foreground with Music Synch and a Cloud Music Player running. After a while from the standby, SoulissApp goes in OFFLINE and stops sending data to my lights, while the music player in the foreground is playing music.

WiFi is active and the music is streamed from a cloud server, so I've full network connectivity at time of this issue.

Let me know if I have to provide more info, running the 1.5.3-testing release of SoulissApp.

**Comment by shineangelic** [comment]
I can't reproduce this, if SoulissApp is foreground it won't stop reproducing because of an OFFLINE state...Even after an hour

Anyone else on this?

**Comment by plinioseniore** [comment]
I suggest to decouple the OFFLINE from the data send method, this out of
Scenario and Programs that should wait ONLINE before proceed.

Dario.

From Mobile.

**Comment by shineangelic** [comment]
apart from the check 'Souliss online' made at the start of nodesDetail activity (to show buttons or not), there is no other reference to the fact Souliss is offline, ie changing this won't solve your issue.
