### ISSUE TITLE
Sleep command for T16 isn't working

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#58]
The SLEEP command for the T16 isn't working, this is assumed to run once the input value is greater than Souliss_T1n_Timed (0x30) and runs for the difference in cycles between the input value and Souliss_T1n_Timed.

So if the input value is 0x31, the lamp will sleep after 1 execution cycle of the timer associated to T16.

Actually from the code I can't understand which value is transmitted while pressing the SLEEP command. In the souliss Typicals.h file has been included the Souliss_T1n_Timed_StdVal    as  0x40 so that 10 execution cycle will expire between the press of the SLEEP and the real OFF of the light.

**Comment by shineangelic** [comment]
The button command depends on the associated android TAG:

btSleep.setTag(it.angelic.soulissclient.model.typicals.Constants.Souliss_T_related);

so, in this case, the sent command is 0xFF (Constants.Souliss_T_related)

**Comment by plinioseniore** [comment]
Ok, I will have a one more try.

Dario.

From Mobile.

**Comment by shineangelic** [comment]
can this be closed?

**Comment by plinioseniore** [comment]
Haven't yet tested, I'm closing the issue and will reopen it in case.

**Comment by plinioseniore** [comment]
SoulissApp sends 0xFF,0xFF,0xFF,0xFF, where only the 0xFF command was expected. The output value goes to GoodNight, but this is not shown in SoulissApp.

**Comment by shineangelic** [comment]
the goodnight is not shown, this is a missing feature. 

But I believe the command to be correct, 2nd,3rd and 4th bytes represent the color chosen at the moment of the sleep command

**Comment by plinioseniore** [comment]
The node knows the last color, is enough just a single 0xff.

From Mobile.
