### ISSUE TITLE
Programs aren't working

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#6]
Hi, I think there's a problem with programs.- Steps to reproduce the bug:
Add a Program with a T11 and Toggle Command, Timed and Repeat Every 30min.

And nothing happens, no start on time, no repeteat every 30 mins.

We're 3 users with the same problem.

Link to the Spanish Post on ML.
https://groups.google.com/forum/#!topic/souliss-es/iJwH2keeRRo

The mobile is connected when the command "is sended"

**Comment by juanpintom** [comment]
Someone have the same problem?

**Comment by lesjaw** [comment]
yes me too..

sometimes after i open soulissapp the program got executed..

**Comment by shineangelic** [comment]
found a bug in program repetitions. Should be fine now

**Comment by lesjaw** [comment]
Still can't execute command..

08-25 22:10:02.704  27699-27699/? D/SoulissApp﹕ mynode nodeId:0
08-25 22:10:02.704  27699-27699/? D/SoulissApp﹕ Filled commandspinner,
nodeId :0
08-25 22:10:09.154  27699-27699/? I/SoulissApp﹕ PERSISTING COMMAND NODEID:0
08-25 22:10:09.244  27699-27699/? D/SoulissApp﹕ new command created,
resultCode = -1
08-25 22:10:09.254  27699-27699/? D/SoulissApp﹕ Found unexecuted commands:1

I was once got the program executed but it didn't turn ON my T11 souliss
node..

**Comment by lesjaw** [comment]
and this is the behaviour..
1. Create a new program
2. Choose Program Target, Node 0 - ON/OFF output with timer, Choose program
   command = Turn ON
3. Choose Timed Activation, set time a couple minute ahead

No program executed, when I sending SoulissApp to background, then reopen
it again I got program executed notfication but nothing happen to Node 0,
and when I tap that notification I got the wrong time, then I check the
program tab, the program I made earlier now gone..

**Comment by shineangelic** [comment]
The program disappears IF it is timed and no repetition is set, this should be already fine. To confirm, activate 'repeat every' so that the program won't disappear once executed.

If you get the notification then the command is executed for sure.

The 'tap notification' issue was real and should be fixed in 1.5.2
