### ISSUE TITLE
Widget for Voice Command

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#68]
Have the microphone on the home screen will be a +1!

**Comment by juanpintom** [comment]
+1

2015-09-19 21:39 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by ribico** [comment]
+1
Il 19/set/2015 11:16 PM, "juanpintom" notifications@github.com ha scritto:

**Comment by plinioseniore** [comment]
Had a try, is working fine. But the Widget is overwritten with the label Souliss Voice Command, for Widgets there should be an external label as per app shortcut.

Also the icon should be without the external rectangle, as is for apps on the home page
