### ISSUE TITLE
Feedback for voice command

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#69]
Voice commands doesn't provide a feedback, even with a not recognized commanf nothing is displayed or spelled.

**Comment by juanpintom** [comment]
Suggestion: Show in the screen (popup) for 1sec the words received on the voice recognition to see if its detected ok.

**Comment by plinioseniore** [comment]
Wouldn't be better if we display if an action has been executed by
SoulissApp?

**Comment by juanpintom** [comment]
Yes, would be better do this in any case, if an action its executed or not, then we can see if voice recognition detected the words I said well or not.

**Comment by shineangelic** [comment]
version 1.5.5 shows a Toast containing the voice recognized and a static info, for es.

"Close damn window - Command sent"

**Comment by plinioseniore** [comment]
That's great!
