### ISSUE TITLE
T58 Don't show the right values

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#7]
I import 1014 and get 722, maybe this line is the problem:
https://github.com/souliss/soulissapp/blob/master/SoulissApp/src/main/java/it/angelic/soulissclient/model/typicals/SoulissTypical58PressureSensor.java#L61

I import with T51 and works well.

Regards

**Comment by plinioseniore** [comment]
Also here https://github.com/souliss/souliss/issues/115

**Comment by shineangelic** [comment]
If T58 uses half-float that is not the only problem.
Can someone confirm the OUT of this typical is in HF format? Or is it a single slot value?
Which is the T58 max value?

**Comment by plinioseniore** [comment]
All T5n and T6n are half-precision floating point. More, on Souliss side it just exist a generic T5n so all T51, T52, ... T58 are exactly the same piece of codes on the board side our of the value passed while requesting the typical list.

**Comment by shineangelic** [comment]
ok, should be fixed
