### ISSUE TITLE
Default Voice Command

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#70]
It would be a plus having a default command for each typical, lets say the toggle for the light, that will help in give shorter commands.

So that a speech "Main Lights" will automatically toggle them, without have to say if we want to shut them ON or OFF.

**Comment by shineangelic** [comment]
I will be adding voice "toggle" command, but it will still be required. Omitting command may be tricky when voice isn't recognized properly.

**Comment by shineangelic** [comment]
The proposed idea could be added to scenarios, ie not requiring "execute scene" sentences...The only scene's name will do.

**Comment by ribico** [comment]
Scenario only is good enough for me.
Il 21/set/2015 10:59 PM, "Alessandro Del Pex" notifications@github.com ha
scritto:

**Comment by plinioseniore** [comment]
+1
