### ISSUE TITLE
T_19: brightness options in sceens not working properly

### ISSUE THREAD

**Issue by Niels-Git** [souliss/soulissapp#71]
The new feature, setting 3 different brightness options while adding  as a command into a scene, is not working properly. As the max. brightness option is working fine, the other two options are just displayed as 'reset' to be chosen while in the command adding procedure. Pls. check the screen-shot below.
The correct wording (English) should be 'medium' and 'low' brightness going along with the desired functionality of course.

You might choose one of these 'reset' named options, but they do not have an effect afterwards when running this scene.

I just can add the German layout, but the problem should be recognizable to you anyway. In terms of code - the two 'reset' options has been already translated in the German version as well.

Pls. just let me know,  if you need more details about this!

![screenshot_2015-09-21-11-55-37](https://cloud.githubusercontent.com/assets/14112664/9989343/eada76a2-6057-11e5-98e3-41c8e070dbc5.jpg)

**Comment by shineangelic** [comment]
I'm sorry for this, I was sure it worked

**Comment by Niels-Git** [comment]
No problem at all - nevertheless, you think you get it going as a matter of principle ?
