### ISSUE TITLE
Add exit button

### ISSUE THREAD

**Issue by FrancoTT** [souliss/soulissapp#76]
Add exit button from the options tab of each window.

**Comment by shineangelic** [comment]
There should never be an "exit" button on Android, just use back. What is your obstacle?

**Comment by FrancoTT** [comment]
Is not an obstacle, is the convenience of the application out of any window

**Comment by shineangelic** [comment]
I'm sorry I can't understand your request

**Comment by FrancoTT** [comment]
Mi è difficile spiegare la richiesta in inglese quindi scrivo in italiano:
nell'applicazione l'unico modo di uscirne in maniera normale (quindi senza utilizzare il task manager di Android) e quella di "ritornare" indietro tramite "freccia indietro" di Android  fino alla schermata di home (quella che appare quando si lancia l'applicazione) e da li, tramite opzioni alla dx in alto, > Esci.
Trovandomi per esempio nei dettagli di un nodo quindi Manuale>Nodo0>Dispositivi>> ON/OFF Digitale con Timer, in questa schermata, nelle opzioni in alto a dx non c'è la voce ESCI ma solo "Rinomina nodo, Cambia Icona nodo, Opzioni".
Questa mancanza si può notare anche nelle precedenti finestre e quindi la richiesta è quella di aggiungere il pulsante ESCI nelle opzioni di tutte le finestre dove manca. Con questa aggiunta ci sarebbe la possibilità di uscire dall'applicazione rapidamente, senza dover ripetutamente premere "freccia indietro" (cosa che può risultare scomoda in dispositivi dove il tasto indietro non è illuminato quindi poco visibile specialmente al buio)

**Comment by shineangelic** [comment]
No, su Android non dovrebbe esserci l'opzione "esci", e infatti non si trova nella maggior parte delle app, certamente non in quelle standard:

"Exit buttons just aren't part of the (intended) Android user experience. You press back or home, and just "Walk away" from the activity"
http://stackoverflow.com/questions/6014028/closing-application-with-exit-button

 Per uscire dall'app, è sufficiente premere "home". Si occupa Android di rimuovovere l'app dalla memoria qualora ne sia richiesta di più. 

Eventualmente, una volta nella home, è possibile chiudere l'app facendo swipe dalla lista delle app recenti..

@hatemalimam ha scritto un ottimo articolo a riguardo:
http://blog.hatemalimam.com/exit-button-in-android-app/
