### ISSUE TITLE
ONLINE / OFFLINE Icon

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#79]
Actually the ONLINE / OFFLINE icon doesn't show the proper information, I suggest to use three states instead of two:
- ONLINE (Green): When the Gateway answer
- SYNCH (Amber): When is waiting for an answer
- OFFLINE (Red): When timeout are expired

Actually, if the user exit in a middle view (like the node view) and the goes back after some time, SoulissApp is offline and you need to go back to the main menu to get it ONLINE. The best would be that it automatically starts to detect the Gateway once back in the app.

SoulissApp should check for OFFLINE/SYNCH/ONLINE but this should not affect the command, that should be always available.

**Comment by shineangelic** [comment]
there is no synch stage, if soulissApp is Offline it will continuosly try to go back online, as the app is opened. A backoff is implemented to reduce traffic when offline time increases.

**Comment by plinioseniore** [comment]
Yep, but in this way you will start in OFFLINE and then you will go in ONLINE and every time that you close and open the app you will see OFFLINE. Use a SYNCH while SoulissApp is connecting and no more than N retries has expired will give a better understanding.

That's my two cents.

**Comment by shineangelic** [comment]
your two cent always costs a lot :dancers:
