### ISSUE TITLE
T19 Sliding bar feedback

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#80]
The sliding bar for T19 get updated from the node, but if you send a new command as value on the sliding, the command is executed correctly but the sliding goes back to the previous value quickly and then to the actual just after it got the data from the node.

Is ok that T19 gets the state update, but the slider should not go back to the previous value but just wait for the new one to get updated.

**Comment by fazioa** [comment]
This happens also in Openhab binding.

Tonino Fazio

2015-10-02 19:51 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
So is a problem of the typical on the node?

**Comment by fazioa** [comment]
Yes I think!

Tonino Fazio

2015-10-02 21:28 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
Got it, there are two problems:
1) The T19 send notification in a way that sucks, I'm changing this
2) SoulissApp after every command from the sliding-bar sends also a data update request, it happen that SoulissApp request this data update too earlier when the Logic_T19 hasn't been fired yet, so that the result of the data update request is the still old value.

So, the slider moves in the position of the new command, gets an older value from the node and moves back, then just after get the notification for the new state and goes to the value inserted by the user.

To fix it, SoulissApp should either send the data update request later than now or skip it, because the node will send in any case the notification just after the stream of command has elapsed.

**Comment by plinioseniore** [comment]
Commit 7d034391f in souliss fix the problem if we run the T19 faster than the communication, fixing on the SoulissApp with one of these two option will solve completely the issue:
- Request the data update not just after the command, or
- Don't request the data update and just wait the for subscription that the node will in any case send

**Comment by shineangelic** [comment]
ok
