### ISSUE TITLE
General purpose combobox

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#83]
In issue souliss/180 is asked for a general purpose combobox, is this feasible or acceptable on SoulissApp.

**Comment by shineangelic** [comment]
As i understood, it's not a generic combobox, it's a behaviur like the "flash" we already have. 

I'd define a new Typical, ie T16B, that supports this extended behaviour

**Comment by plinioseniore** [comment]
Yes, but is too custom and specific for a single use, if we should do it, it will be better to have a generic combox with renamable fields. Then every one can use it as he prefer.

**Comment by juanpintom** [comment]
Yes, isn't a single behaviour, with WS2812 indexable led strips we can make
effects like rainbow, bulbs, knight rider :O and others, you can see videos
about on youtube and this video maded by MeroFilosofo at Spanish Forum:
https://groups.google.com/forum/#!topic/souliss-es/ya3akohGM1U

Regards

2015-10-07 11:46 GMT+02:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
ok, an array of effects then? What about the T16b ?

**Comment by juanpintom** [comment]
A T16b is ok, we'll do the same on the framework to integrate the array of
effects, in fact the effects are integrated now with the code suggested by
Merofilosofo, but he is using a T15 (I don't know why)

This new T16b will be a Typical for Indexable Led Strips (WS2812B and
others) and the T16 for "standard" RGB led Strips.

Regards

2015-10-07 18:58 GMT+02:00 Alessandro Del Pex notifications@github.com:
