### ISSUE TITLE
tag on SoulissApp

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#9]
FOR SOULISSAPP

1) La scheda TAG con la sola voce di default non è visibile in homepage

What steps will reproduce the problem?

...da App appena installata:
1. Rinomino TAG Preferiti in "rientro casa"
2. Inserisco secondo TAG
3. Provo a eliminare il TAG "rientro casa", ricevo "Can't remove default Favourite Tag"
4. Provo ad eliminare il secondo TAG, ricevo "Can't remove default Favourite Tag"

What is the expected output? What do you see instead?
Mi aspetterei, pur avendo il TAG di default, di poterlo cancellare. 
In alternativa di poter cancellare quello di default e di poterne lasciare almeno uno in sua vece.
Al momento ho due TAG entrambi NON PIU' CANCELLABILI.

What version of the app and framework are you using?
1.5.1

**Comment by plinioseniore** [comment]
From https://github.com/souliss/souliss/issues/114

**Comment by shineangelic** [comment]
you won't be able to rename predefined "Fav" TAG

the box will appear if some fav is defined
