### ISSUE TITLE
Toast "Unsupported Command"

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#90]
Starting from commit 7db15711e, the node can return functional code 0x83 to notify an error with a command. Display a toast with "Unsupported Command" when this frame is received.

**Comment by shineangelic** [comment]
0x83 won't fit in a byte, I don't know if using an int would do...

**Comment by plinioseniore** [comment]
A byte is up to 0xFF :)

**Comment by shineangelic** [comment]
not in Java, where Byte is signed. 
Could we "lower" the functional code?

**Comment by plinioseniore** [comment]
Java sucks?

Use -0x3 it has same binary value of 0x83.

Dario.

From Mobile.
