### ISSUE TITLE
Traslation missing FUNZIONI and OPZIONI words on Sidebar

### ISSUE THREAD

**Issue by juanpintom** [souliss/soulissapp#92]
On the sidebar of the app I can see FUNZIONI and OPZIONI words but I cannot find on the sourcecode, any hint?

Regards

**Comment by shineangelic** [comment]
It's a missing translation string, I will fix it.

Thank you Juan, as always.
Alessandro

2015-10-22 17:35 GMT+02:00 juanpintom notifications@github.com:

**Comment by juanpintom** [comment]
;)

Thanks to you :P

Regards

2015-10-23 12:07 GMT+02:00 Alessandro Del Pex notifications@github.com:

**Comment by shineangelic** [comment]
closed. Please addo your localised strings:

https://github.com/souliss/soulissapp/blob/master/soulissLib/src/main/res/values-es/strings.xml
