### ISSUE TITLE
Zozzariello will never die!

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#95]
Zozzariello is the best piece of software in SoulissApp and need aliases based on the names of the devices.

We need a new sintax that allow to turn on the lamp without have to specify command in hex and slot position, but human readable text.

**Comment by juanpintom** [comment]
+1 Good idea

2015-10-26 8:11 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
KILL ZOZZARIELLO!!!

**Comment by juanpintom** [comment]
What??? :S I dont undestand :(

Regards

2015-10-27 22:00 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
Intent and Tasker+Automate native integration will remove the need of
Zozzariello.

Alessandro is looking to kill Zozzariello from long time.

Dario.

From Mobile.

**Comment by juanpintom** [comment]
Ah! Ok, Am agree with that, with intent on Souliss Zozziarello will be
obsolete, regards.

2015-10-27 23:55 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
poi sono io, lo schizo.
