### ISSUE TITLE
Itent for interaction with external application

### ISSUE THREAD

**Issue by plinioseniore** [souliss/soulissapp#96]
Design of Intents for interaction with Tasker and Automate (as well as other automation application for Android) has started, details here (https://github.com/souliss/souliss/wiki/SoulissApp-Intents).

**Comment by juanpintom** [comment]
+1 Good!

2015-10-27 22:01 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by shineangelic** [comment]
https://github.com/souliss/souliss/wiki/SoulissApp-API

**Comment by juanpintom** [comment]
Ok Automate its installed, waiting your apk update =)

Regards

2015-10-28 0:51 GMT+01:00 Alessandro Del Pex notifications@github.com:

**Comment by shineangelic** [comment]
Juan you're always up to date :)

**Comment by juanpintom** [comment]
I try! :P I not seen yet the "it.angelic.receivers.AutomateReceiver" on
Receiver Class :(

Regards

2015-10-28 11:30 GMT+01:00 Alessandro Del Pex notifications@github.com:

**Comment by shineangelic** [comment]
Yes, it will be in next version

Ale
Il 28/ott/2015 16:15, "juanpintom" notifications@github.com ha scritto:
