### ISSUE TITLE
TAG rename do not refresh

### ISSUE THREAD

**Issue by ribico** [souliss/soulissapp#98]
In tag view if you rename a tag the new name is not displayed unless you exit and enter back in the tag view

**Comment by ribico** [comment]
The same issue can be seen when renaming typical in Manual view. A node refresh is needed to update the typical name after rename

**Comment by shineangelic** [comment]
I can't reproduce it, it works until you try to rename default "favourite" TAG.

As for manual view, I tested both entry point:
1) long-press on typical list -> rename Device
2) little three dots aside the list -.> rename Device

and they both refresh the name in the list correctly, the code hasn't changed from a long ago.

Anyway, I removed the restriction to rename favourite TAG.
